PycharmProjects/mystaffingsite/mystaffingsite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('staffing/', include('staffing.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PycharmProjects/mystaffingsite/staffing/urls.py
from django.urls import path
from . import views

app_name = 'staffing'

urlpatterns =[
    path('', views.landing, name= 'landing'),
    path('clientSignupOrLogin/', views.clientSignupOrLogin, name= 'clientSignupOrLogin'),
    path('applicantSignupOrLogin/', views.applicantSignupOrLogin, name= 'applicantSignupOrLogin'),
    path('managerLogin/', views.managerLogin, name= 'managerLogin'),
    path('recruiterLogin/', views.recruiterLogin, name= 'recruiterLogin'),
    path('applicantDashboard/<int:applicant_id>/', views.applicantDashboard, name= 'applicantDashboard'),
    path('clientDashboard/<int:client_id>/', views.clientDashboard, name= 'clientDashboard'),
    path('clientDashboard/<int:client_id>/newPosting/', views.newPosting, name= 'newPosting'),
    path('recruiterDashboard/<int:recruiter_id>/', views.recruiterDashboard, name= 'recruiterDashboard'),
    path('recruiterDashboard/<int:recruiter_id>/searchJobPosting/', views.searchJobPosting, name= 'searchJobPosting'),
    path('recruiterDashboard/<int:recruiter_id>/searchApplicant/', views.searchApplicant, name= 'searchApplicant'),
    path('managerDashboard/<int:manager_id>/', views.managerDashboard, name= 'managerDashboard'),
    path('managerDashboard/<int:manager_id>/newRecruiter/', views.newRecruiter, name= 'newRecruiter'),
    path('managerDashboard/<int:manager_id>/editRecruiter/<int:recruiter_id>/', views.editRecruiter, name='editRecruiter'),
    path('managerDashboard/removeRecruiter/<int:recruiter_id>/', views.removeRecruiter, name='removeRecruiter'),
    path('logoutView/', views.logoutView, name = 'logoutView'),
]

PycharmProjects/mystaffingsite/staffing/forms.py
from django import forms
from .models import Client, Applicant, Recruiter

skills = (('Java', 'Java'), ('C/C++','C/C++'), ('Go', 'Go'), ('JavaScript', 'JavaScript'), ('Python', 'Python'),
          ('Lua', 'Lua'), ('Shell', 'Shell'), ('PHP', 'PHP'), ('MySQL', 'MySQL'), ('Android', 'Android'))

class ClientSignupForm(forms.ModelForm):

    password = forms.CharField(widget= forms.PasswordInput)

    class Meta:
        model = Client
        exclude = ['user']

class ClientLoginForm(forms.Form):

    username = forms.CharField(max_length=50)
    password = forms.CharField(max_length=50, widget= forms.PasswordInput)

class ApplicantSignupForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = Applicant
        exclude = ['user', 'skills', 'resume_file']

class ApplicantLoginForm(forms.Form):
    username = forms.CharField(max_length=50)
    password = forms.CharField(max_length=50, widget=forms.PasswordInput)

class NewPostingForm(forms.Form):

    job_title = forms.CharField(max_length=100)
    skills = forms.MultipleChoiceField( required=True, widget= forms.CheckboxSelectMultiple,
                                        choices= skills
    )

class ManagerLoginForm(forms.Form):
    username = forms.CharField(max_length=50)
    password = forms.CharField(max_length=50, widget=forms.PasswordInput)

class NewRecruiterForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = Recruiter
        exclude = ['user']

class RecruiterLoginForm(forms.Form):
    username = forms.CharField(max_length=50)
    password = forms.CharField(max_length=50, widget=forms.PasswordInput)

class UploadResumeForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()

PycharmProjects/mystaffingsite/staffing/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect, get_object_or_404
from staffing.models import Client
from django.contrib.auth import authenticate, login, logout
from .forms import ClientSignupForm, ClientLoginForm, ApplicantSignupForm, ApplicantLoginForm, NewPostingForm, ManagerLoginForm, NewRecruiterForm, RecruiterLoginForm, UploadResumeForm
from .models import Client, Applicant, ApplicantSkill, JobPosting, JobPostingSkill, Recruiter
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import permission_required, user_passes_test, login_required
from django.db.models import Q
from operator import or_
from functools import reduce

from pdfminer.pdfparser import PDFParser, PDFDocument
from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.converter import PDFPageAggregator
from pdfminer.layout import LAParams, LTTextBox, LTTextLine

import datetime
import PyPDF2
from pdfrw import PdfReader

#Global declarations
skills = ['Java', 'C/C++', 'Go', 'JavaScript', 'Python', 'Lua', 'Shell', 'PHP', 'MySQL', 'Android']

def landing(request):
    """Asks user about their role"""
    return render(request, 'staffing/landing.html')

def managerLogin(request):

    if request.method == 'POST':
        form = ManagerLoginForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            manager = authenticate(username=username, password=password)
            try:
                mangr = manager.manager
            except:
                return redirect('staffing:managerLogin')

            if manager is not None and manager.is_active:
                login(request, manager)
                return HttpResponseRedirect(reverse('staffing:managerDashboard', args=(manager.manager.id,)))
            else:
                return render(request, 'staffing/managerLogin.html', {'form': form})

    else:
        form = ManagerLoginForm()
        return render(request, 'staffing/managerLogin.html', {'form':form})

def recruiterLogin(request):

    if request.method == 'POST':

        form = RecruiterLoginForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            recruiter = authenticate(username=username, password=password)

            try:
                recr = recruiter.recruiter
            except:
                return redirect('staffing:recruiterLogin')

            if recruiter is not None and recruiter.is_active:
                login(request, recruiter)
                return HttpResponseRedirect(reverse('staffing:recruiterDashboard', args=(recruiter.recruiter.id,)))
            else:
                return render(request, 'staffing/recruiterLogin.html', {'form': form})

    else:
        form = RecruiterLoginForm()

        return render(request, 'staffing/recruiterLogin.html', {'form':form})

def recruiterDashboard(request, recruiter_id):

    if not request.user.is_authenticated:
        return redirect('staffing:recruiterLogin')

    try:
        recruiter = request.user.recruiter
    except:
        print("recruiter is none")
        return redirect('staffing:recruiterLogin')

    if request.method == 'POST':
        hello = "hi"
    else:
        job_postings = JobPosting.objects.all()
        applicants = Applicant.objects.all()

        return render(request, 'staffing/recruiterDashboard.html', {'job_postings':job_postings, 'applicants':applicants, 'recruiter':recruiter})

def searchJobPosting(request, recruiter_id):

    if not request.user.is_authenticated:
        return redirect('staffing:recruiterLogin')

    try:
        recruiter = request.user.recruiter

    except:
        return redirect('staffing:recruiterLogin')

    res = None

    if request.method == 'POST':

        search_string = request.POST['jobPosting_search']
        search_string = search_string.strip()
        anded_skills = search_string.split("or")

        ored_skills_temp = [x.split("and") for x in anded_skills]

        ored_skills = [[skill.replace(" ", "") for skill in skills] for skills in ored_skills_temp]

        res = JobPosting.objects.filter(reduce(or_, [ Q(skills__contains=skills) for skills in ored_skills]))

        return render(request, 'staffing/searchJobPosting.html', {'res':res, 'recruiter':recruiter})

    else:
        return render(request, 'staffing/searchJobPosting.html', {'res':res, 'recruiter':recruiter})

def searchApplicant(request, recruiter_id):


    if not request.user.is_authenticated:
        return redirect('staffing:applicantLogin')
    try:
        recruiter = request.user.recruiter

    except:
        return redirect('staffing:recruiterLogin')

    res = None

    if request.method == 'POST':

        search_string = request.POST['applicant_search']
        search_string = search_string.strip()
        anded_skills = search_string.split("or")

        ored_skills_temp = [x.split("and") for x in anded_skills]

        ored_skills = [[skill.replace(" ", "") for skill in skills] for skills in ored_skills_temp]
        print(ored_skills)
        res = Applicant.objects.filter(reduce(or_, [Q(skills__contains=skills) for skills in ored_skills]))

        print(res)
        return render(request, 'staffing/searchApplicant.html', {'res': res, 'recruiter':recruiter})


    else:
        return render(request, 'staffing/searchApplicant.html', {'res': res, 'recruiter':recruiter})

def managerDashboard(request, manager_id):

    if not request.user.is_authenticated:
        return redirect('staffing:managerLogin')

    try:
        manager = request.user.manager
    except:
        print("manager is None")
        return redirect('staffing:managerLogin')

    if request.method == 'POST':

        hello = "hi"

    else:

        recruiters = Recruiter.objects.all()
        return render(request, 'staffing/managerDashboard.html', {'recruiters':recruiters, 'manager': manager})

def newRecruiter(request, manager_id):

    if not request.user.is_authenticated:
        return redirect('staffing:managerLogin')

    try:
        manager = request.user.manager

    except:
        return redirect('staffing:managerLogin')

    if request.method == 'POST':

        form = NewRecruiterForm(request.POST)

        if form.is_valid():

            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            phone_number = form.cleaned_data['phone_number']
            email = form.cleaned_data['email']
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            try:
                user = User.objects.create_user(
                    username=username,
                    password=password
                )
            except :
                return HttpResponseRedirect(reverse('staffing:managerDashboard', args=(manager.id,)))

            recruiter = Recruiter.objects.create(
                user = user,
                first_name = first_name,
                last_name=last_name,
                phone_number=phone_number,
                email=email,
                username=username,
                password=password,
            )

        return HttpResponseRedirect(reverse('staffing:managerDashboard', args=(manager.id,)))

    else:
        form = NewRecruiterForm()

        return render(request, 'staffing/newRecruiter.html', {'form':form, 'manager':manager})

def editRecruiter(request, manager_id, recruiter_id):

    if not request.user.is_authenticated:
        return redirect('staffing:managerLogin')
    try:
        manager = request.user.manager

    except:
        return redirect('staffing:managerLogin')

    recruiter = get_object_or_404(Recruiter, id=recruiter_id)

    if request.method == 'POST':

        form = NewRecruiterForm(request.POST, instance=recruiter)
        if form.is_valid():
            form.save()

        return HttpResponseRedirect(reverse('staffing:managerDashboard', args=(manager.id,)))
    else:
        form = NewRecruiterForm(None, instance=recruiter)

        return render(request, 'staffing/editRecruiter.html', {'form':form, 'recruiter':recruiter, 'manager':manager})

def removeRecruiter(request, recruiter_id):

    if not request.user.is_authenticated:
        return redirect('staffing:managerLogin')
    try:
        manager = request.user.manager

    except:
        return redirect('staffing:managerLogin')

    rec = Recruiter.objects.get(id=recruiter_id)
    username = rec.username
    User.objects.filter(username=username).delete()
    Recruiter.objects.filter(id=recruiter_id).delete()
    return HttpResponseRedirect(reverse('staffing:managerDashboard', args=(manager.id,)))


def clientSignupOrLogin(request):
    signup_form = ClientSignupForm()
    login_form = ClientLoginForm()

    if request.method == 'POST':

        #SIGNUP
        if request.POST.get('submit') == 'Signup':

            form = ClientSignupForm(request.POST)



            if form.is_valid():

                company_name = form.cleaned_data['company_name']
                location = form.cleaned_data['location']
                phone_number = form.cleaned_data['phone_number']
                email = form.cleaned_data['email']
                username = form.cleaned_data['username']
                password = form.cleaned_data['password']

                user = User.objects.create_user(
                    username= username,
                    password = password
                )

                client = Client.objects.create(
                    user = user,
                    username=username,
                    password=password,
                    company_name=company_name,
                    location = location,
                    phone_number = phone_number,

PycharmProjects/mystaffingsite/staffing/templates/staffing/applicantDashboard.html
{% extends "staffing/base.html"%}

{% block body %}
<div class="jumbotron">
    <p><h3>Welcome {{ applicant.first_name }}!</h3></p>
    <hr>
    <h4>Application Submission</h4>
    <form action="{% url 'staffing:applicantDashboard' applicant.id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ file_form }}

        <button type="submit" name="submit" value = "submit_file">Submit File</button>
    </form>

    <hr width="50%">
    <p>No pdf file? Submit the form below</p>
    <form action="{% url 'staffing:applicantDashboard' applicant.id %}" method="POST">
        {% csrf_token %}

        <label for = "first_name">First Name</label>
        <input type="text" id = "first_name" name = "first_name" value=""> <br>

        <label for = "last_name">Last Name</label>
        <input type="text" id = "last_name" name = "last_name" value=""> <br>

        <label for = "email">Email</label>
        <input type="text" id = "email" name = "email" value=""> <br>

        <p>Skills</p>
        {% for skill in skills%}
            <label for = "skills">{{ skill }}</label>
            <input type="checkbox" id = "skills" name = "skills" value="{{ skill }}"> <br>
        {% endfor %}
        <br>
        <button type="submit" name="submit" value = "submit_form" class = "btn btn-primary">Submit Form</button>
    </form>
</div>
{% endblock %}

PycharmProjects/mystaffingsite/staffing/templates/staffing/base.html
{% load bootstrap3 %}
{% load static %}
<html>
<head> 
    <title>Staffing Website</title> 
    <link rel = "stylesheet" href = "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> 
    <link rel = "stylesheet" type="text/css" href="{% static 'staffing/style.css' %}" />
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<style>
    table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
    border: none;
    }
    th, td {
        padding: 15px;
    }
</style>
</head>

<body>
    <div class="container">
        {% block body%}{% endblock %}
    </div>

{% block footer %}
<p style="margin-left: 20px"><a href="{% url 'staffing:logoutView'  %}" class="btn btn-danger">Logout</a></p>
{% endblock %}

<script>
    $(function() {

    $('#login-form-link').click(function(e) {
		$("#login-form").delay(100).fadeIn(100);
 		$("#register-form").fadeOut(100);
		$('#register-form-link').removeClass('active');
		$(this).addClass('active');
		e.preventDefault();
	});
	$('#register-form-link').click(function(e) {
		$("#register-form").delay(100).fadeIn(100);
 		$("#login-form").fadeOut(100);
		$('#login-form-link').removeClass('active');
		$(this).addClass('active');
		e.preventDefault();
	});

});
</script>
</body>
</html>

PycharmProjects/mystaffingsite/staffing/templates/staffing/clientDashboard.html
{% extends "staffing/base.html"%}

{% block body %}
<div class = "jumbotron">
    <p><h3>Welcome {{ client.username }}!</h3></p>
    <hr>
    <p><a href="{% url 'staffing:newPosting' client.id %}" >Add a Job Posting</a></p>
    <h3>My Job Postings</h3>
    <ol>
        {% for job_posting in job_postings %}
        <li>{{ job_posting.title }} -
        {% for skill in job_posting.skills %}
            {{ skill }}{% if not forloop.last %} ,{% else %}.{% endif %}
        {% endfor %}
        </li>
        {% endfor %}
    </ol>
</div>
{% endblock %}

PycharmProjects/mystaffingsite/staffing/templates/staffing/clientSignupOrLogin.html
{% extends "staffing/base_signup_login.html"%}

{% block action_login%}
    action = "{% url 'staffing:clientSignupOrLogin' %}"
{% endblock %}

{% block action_signup %}
    action="{% url 'staffing:clientSignupOrLogin' %}"
{% endblock %}

{% block login_form %}
    {{ login_form }}
{% endblock %}

{% block signup_form %}
    {{ signup_form }}
{% endblock %}

{% block footer %}{% endblock %}

PycharmProjects/mystaffingsite/staffing/templates/staffing/editRecruiter.html
{% extends "staffing/base.html"%}

{% block body %}
<div class="jumbotron">
    <p class = "lead">Edit the Recruiter info below.</p>
    <hr>
    <form action="{% url 'staffing:editRecruiter' manager.id recruiter.id %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            {{ form }}
        </div>

        <button type="submit" name="submit" class="btn btn-primary">Update</button>
    </form>
</div>
{% endblock %}

PycharmProjects/mystaffingsite/staffing/templates/staffing/landing.html
{% extends "staffing/base.html"%}

{% block body %}
<div class = "jumbotron">
    <h1 class="display-3">Welcome to The Staffing Website!</h1>
    <p class = "lead"> The Staffing Website connects recruiters and job seekers. Finding a job or talent has never been easier! </p>
    <hr class = "my-4">
    <p>Please select whether you are a recruiter or a job seeker below. </p>
    <div class = "row">
        <div class = "col-sm">
            <p class="lead"><a href="{%url 'staffing:clientSignupOrLogin' %}" class="btn btn-success">Posting a job</a></p>
        </div>
        <div class = "col-sm">
        <p class="lead"><a href="{%url 'staffing:applicantSignupOrLogin' %}" class="btn btn-primary">Applying for a job</a></p>
        </div>
        <div class = "col-sm">
        <p class="lead"><a href="{% url 'staffing:managerLogin' %}" class="btn btn-danger">Manager login</a></p>
        </div>
        <div class = "col-sm">
        <p class="lead"><a href="{% url 'staffing:recruiterLogin' %}" class="btn btn-warning">Recruiter login</a></p>
        </div>
    </div>
</div>
{% endblock %}
{% block footer %}{% endblock %}

PycharmProjects/mystaffingsite/staffing/templates/staffing/managerDashboard.html
{% extends "staffing/base.html"%}

{% block body %}
<div class="jumbotron">
    <p><h3>Welcome {{ manager.first_name }}!</h3></p>
    <hr>
    <p><a href="{% url 'staffing:newRecruiter' manager.id %}" class="btn btn-success">Add a recruiter</a></p>

    <table>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Phone Number</th>

        </tr>
        {% for recruiter in recruiters %}
        <tr>
            <td>{{ recruiter.first_name }}</td>
            <td>{{ recruiter.last_name }}</td>
            <td>{{ recruiter.email }}</td>
            <td>{{ recruiter.phone_number }}</td>
            <td><a href="{% url 'staffing:editRecruiter' manager.id recruiter.id %}" class="btn btn-warning">Edit</a></td>
            <td><a href="{% url 'staffing:removeRecruiter' recruiter.id %}" class="btn btn-danger">Remove</a></td>
        </tr>
        {% endfor %}
    </table>

</div>
{% endblock %}

PycharmProjects/mystaffingsite/staffing/templates/staffing/managerLogin.html
{% extends "staffing/base.html"%}

{% block body %}
<div class = "row">
    <div class="col-md-6 col-md-offset-6">
        <div class="panel panel-login">
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">

                        <form id="login-form" action = "{% url 'staffing:managerLogin' %}" method="POST" role="form" style= "display: block;">
                            {% csrf_token %}
                            <div class="form-group">
                                {{ form }}
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-sm-12 col-sm-offset-3">
                                        <input type="submit" id="login-submit" name="login" tabindex="4" class="form-control btn btn-login" value = "Login">
                                    </div>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block footer %}{% endblock %}

PycharmProjects/mystaffingsite/staffing/templates/staffing/newPosting.html
{% extends "staffing/base.html"%}

{% block body %}
<div class = "jumbotron">
    <h3>Add Job Title and Skills</h3>
    <form action="{% url 'staffing:newPosting' client.id %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <button type="submit" name="submit" class = "btn btn-primary">Submit Posting</button>
    </form>
</div>
{% endblock %}

PycharmProjects/mystaffingsite/staffing/templates/staffing/newRecruiter.html
{% extends "staffing/base.html"%}

{% block body %}
<div class="jumbotron">
    <p class = "lead">Fill in the information to add a new recruiter.</p>
    <hr>
    <form action="{% url 'staffing:newRecruiter' manager.id %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
        {{ form }}
        </div>
        <button type="submit" name="submit" class="btn btn-primary">Add Recruiter</button>
    </form>
</div>
{% endblock %}

PycharmProjects/mystaffingsite/staffing/templates/staffing/recruiterDashboard.html
{% extends "staffing/base.html"%}

{% block body %}
<div class = "jumbotron">
    <h3>Welcome {{ recruiter.first_name }}!</h3>
    <hr>
    <p><a href="{% url 'staffing:searchJobPosting' recruiter.id %}" class="btn btn-info">Search Job Postings by skill</a></p>
    <p><a href="{% url 'staffing:searchApplicant' recruiter.id %}" class="btn btn-primary">Search Applicants by skill</a></p>
    <br>
    <h3>Job Postings</h3>

    <table>
        <tr>
            <th>Client</th>
            <th>Job Title</th>
        </tr>
        {% for job_posting in job_postings %}
        <tr>
            <td>{{ job_posting.client }}</td>
            <td>{{ job_posting.title }}</td>
        </tr>
        {% endfor %}
    </table>
    <br>
    <h3>Applicants</h3>

    <table>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
        </tr>
        {% for applicant in applicants %}
        <tr>
            <td>{{ applicant.first_name }}</td>
            <td>{{ applicant.last_name }}</td>
        </tr>
        {% endfor %}
    </table>

</div>
{% endblock %}

PycharmProjects/mystaffingsite/staffing/templates/staffing/recruiterLogin.html
{% extends "staffing/base.html"%}

{% block body %}
<div class = "row">
    <div class="col-md-6 col-md-offset-6">
        <div class="panel panel-login">
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">

                        <form id="login-form" action = "{% url 'staffing:recruiterLogin' %}" method="POST" role="form" style= "display: block;">
                            {% csrf_token %}
                            <div class="form-group">
                                {{ form }}
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-sm-12 col-sm-offset-3">
                                        <input type="submit" id="login-submit" name="login" tabindex="4" class="form-control btn btn-login" value = "Login">
                                    </div>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block footer %}{% endblock %}

PycharmProjects/mystaffingsite/staffing/templates/staffing/searchApplicant.html
{% extends "staffing/base.html"%}

{% block body %}
<div class = "jumbotron">
    <form action="{% url 'staffing:searchApplicant' recruiter.id %}" method = "POST">
        {% csrf_token %}

        <label class ="lead" for = "applicant_search">Input skills separated by "and" and/or "or"</label><br>
        <hr>
        <textarea class="form-control" id = "applicant_search" name="applicant_search" rows="5" cols="50"></textarea><br>
        <button type="submit" name="submit" class = "btn btn-primary">Search</button>



        {% if res %}
            <hr>
            <br>
            <p><h4>Search Results</h4></p>
            <table>
                <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Skills</th>
                </tr>
            {% for applicant in res %}
                <tr>
                    <td>{{ applicant.first_name }}</td>
                    <td>{{ applicant.last_name }}</td>
                    <td>{{ applicant.skills }}</td>
                </tr>
            {% endfor %}
            </table>
        {% endif %}
    </form>
</div>
{% endblock %}

PycharmProjects/mystaffingsite/staffing/templates/staffing/searchJobPosting.html
{% extends "staffing/base.html"%}

{% block body %}
<div class = "jumbotron">
    <form action="{% url 'staffing:searchJobPosting' recruiter.id%}" method = "POST">
        {% csrf_token %}

        <label class ="lead" for = "jobPosting_search">Input skills separated by "and" and "or"</label><br>
        <hr>
        <textarea id = "jobPosting_search" name="jobPosting_search"  class="form-control" rows="5" cols="50"></textarea><br>
        <button type="submit" name="submit" class = "btn btn-primary">Search</button>


        {% if res %}
            <hr>
            <br>
            <p><h4>Search Results</h4></p>
            <table>
                <tr>
                    <th>Client</th>
                    <th>Job Posting Title</th>
                    <th>Skills</th>
                </tr>
            {% for job_posting in res %}
                <tr>
                    <td>{{ job_posting.client.company_name }}</td>
                    <td>{{ job_posting.title }}</td>
                    <td>{{ job_posting.skills }}</td>
                </tr>
            {% endfor %}
            </table>
        {% endif %}
    </form>
</div>
{% endblock %}}